<?php

function banyan_theme_preprocess_page_title(&$variables) {
  if (isset($variables['title'])) {
    $title = (string) $variables['title'];
    \Drupal::logger('banyan_theme')->notice('Title before: @title', ['@title' => $title]);
    $title = preg_replace('/<em class="placeholder">(.*?)<\/em>/', '$1', $title);
    $variables['title'] = \Drupal\Core\Render\Markup::create($title);
    \Drupal::logger('banyan_theme')->notice('Title after: @title', ['@title' => $title]);
  }
}
